Routes:
  - device: "crossbar"
    links: 
      - {src: "3/0", dst: "5/0", enable: 1}
      - {src: "3/1", dst: "6/0", enable: 1}
      - {src: "3/2", dst: "7/0", enable: 1}
      - {src: "3/3", dst: "8/0", enable: 1}
  - device: "4ac10000.syscon:formatter@120"
    links: 
      - {src: "0/0", dst: "1/0", enable: 1}
      - {src: "0/1", dst: "1/1", enable: 1}
      - {src: "0/2", dst: "1/2", enable: 1}
      - {src: "0/3", dst: "1/3", enable: 1}
  - device: "csidev-4ad40000.csi"
    links: 
      - {src: "0/0", dst: "1/0", enable: 1}
      - {src: "0/1", dst: "1/1", enable: 1}
      - {src: "0/2", dst: "1/2", enable: 1}
      - {src: "0/3", dst: "1/3", enable: 1}
  - device: "max96724 3-002e"
    links: 
      - {src: "0/0", dst: "4/0", enable: 1}
      - {src: "1/0", dst: "4/1", enable: 1}
      - {src: "2/0", dst: "4/2", enable: 1}
      - {src: "3/0", dst: "4/3", enable: 1}
  - device: "max96717 8-0040"
    links: 
      - {src: "0/0", dst: "1/0", enable: 1}
  - device: "max96717 9-0040"
    links: 
      - {src: "0/0", dst: "1/0", enable: 1}
  - device: "max96717 10-0040"
    links: 
      - {src: "0/0", dst: "1/0", enable: 1}
  - device: "max96717 11-0040"
    links: 
      - {src: "0/0", dst: "1/0", enable: 1}
MediaLinks:
  - {src: "max96724 3-002e:4", dst: "csidev-4ad40000.csi:0", enable: 1}