Routes:
  - device: "csidev-4ad30000.csi"
    links:
      - {src: "0/0", dst: "1/0", enable: 1}

  - device: "4ac10000.syscon:formatter@20"
    links:
      - {src: "0/0", dst: "1/0", enable: 1}

  - device: "csidev-4ad40000.csi"
    links:
      - {src: "0/0", dst: "1/0", enable: 1}

  - device: "4ac10000.syscon:formatter@120"
    links:
      - {src: "0/0", dst: "1/0", enable: 1}

  - device: "crossbar"
    links:
      - {src: "2/0", dst: "5/0", enable: 1}
      - {src: "3/0", dst: "6/0", enable: 1}

MediaLinks:
  - {src: "tevs 1-0048:0", dst: "csidev-4ad30000.csi:0", enable: 1}
  - {src: "tevs 3-0048:0", dst: "csidev-4ad40000.csi:0", enable: 1}