Routes:
  - device: "crossbar"
    links: 
      - {src: "2/0", dst: "5/0", enable: 1}
      - {src: "3/0", dst: "6/0", enable: 1}
MediaLinks:
  - {src: "tevs 1-0048:0", dst: "csidev-4ad30000.csi:0", enable: 1}
  - {src: "tevs 3-0048:0", dst: "csidev-4ad40000.csi:0", enable: 1}